config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  get 'apropos', to: 'pages#apropos'
  get 'offreparticuliers', to: 'pages#offreparticuliers'
  get 'offreentreprises', to: 'pages#offreentreprises'
  get 'temoignages', to: 'pages#temoignages'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def apropos
  end

  def monoffre
  end

  def temoignages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title><%= yield(:title) || "Open UP" %></title>
  <meta name="description"
      content="<%= (yield(:description) || "Coaching & Consulting").squish %>">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "shared/navbar" %>
  <%= yield %>
  <%= render "shared/footer" %>
    <!-- For inserting some analytics script (GA, Mixpanel..) -->
  <%= render "shared/analytics" %>
  <%= javascript_include_tag "application" %>

</body>
</html>

app/views/pages/apropos.html.erb
<h1>Pages#apropos</h1>
<p>Find me in app/views/pages/apropos.html.erb</p>

app/views/pages/home.html.erb
<body>


  <div class="row">
    <div id="banner-home" style= "background: linear-gradient(rgba(0, 9, 0, 0.15),rgba(0, 9, 0, 0.15)),url(<%= asset_path 'banner.png' %>); background-size:cover;" class="col-xs-12">
      <div class="row padded fadeInAndSlideDown">
        <div>
          <h1>Découvrez comment retrouver sérénité et confiance face aux défis de votre vie.</h1>
        </div>
      </div>
      <div class="row text-center" style="position: static; padding-top: 90px">
        <div class="col-xs-12">
          <div id="trigger1" style="text-align:center;">
            <%= link_to "#trigger2" do %>
              <i class="fa fa-angle-down pulse scroll-btn-white" style="font-size: 55px"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid text-center">
    <div class="row padded">
      <div class="col-xs-offset-2 col-xs-8 bordered-orange">
        <h2>Coaching particuliers :</h2>
      </div>
    </div>
    <div class="row">
      <%= link_to "/monoffre" do %>
        <div class="col-xs-12 col-sm-6 col-md-3 image-section-particuliers" style="background: url(<%= asset_path 'sérennité.png' %>)">
          <h3>Développer votre sérénité</h3>
          <p>Gérer son stress</p>
          <p>Prévenir les burn-outs</p>
          <p>Améliorer son équilibre de vie</p>
        </div>
      <% end %>
      <%= link_to "/monoffre" do %>
        <div class="col-xs-12 col-sm-6 col-md-3 image-section-particuliers" style="background: url(<%= asset_path 'efficacité.png' %>)">
          <h3>Booster votre efficacité pro</h3>
          <p>Améliorer sa communication,</p>
          <p>sa performance,</p>
          <p>et sa motivation</p>
        </div>
      <% end %>
      <%= link_to "/monoffre" do %>
        <div class="col-xs-12 col-sm-6 col-md-3 image-section-particuliers" style="background: url(<%= asset_path 'transition.png' %>)">
          <h3>Réussir votre transition de vie</h3>
          <p>Trouver sa voie, un nouveau projet professionnel</p>
          <p>Partir en expatriation</p>
        </div>
      <% end %>
      <%= link_to "/monoffre" do %>
        <div class="col-xs-12 col-sm-6 col-md-3 image-section-particuliers" style="background: url(<%= asset_path 'etudiants.png' %>)">
          <h3>Orientation jeunes</h3>
          <p>Choisir son orientation</p>
          <p>Développer sa confiance</p>
          <p>Réussir ses examens</p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="row padded text-center">
      <div class="col-xs-offset-2 col-xs-8 bordered-orange">
        <h2>Coaching entreprises :</h2>
      </div>
    </div>
    <div style= "background: url(<%= asset_path 'pro.png' %>); background-size:cover;" class="col-xs-12">
      <div class="row padded banner-pro">
        <h3>Développez le bien-être de vos salariés</h3>
        <div class="row padded text-center">
          <div class="col-xs-4" style="color: white;">
            <h4>Gestion du stress</h4>
          </div>
          <div class="col-xs-4">
            <h4>Efficacité et motivation</h4>
          </div>
          <div class="col-xs-4">
            <h4>Expatriation et transition</h4>
          </div>
        </div>
      </div>
    </div>

  </div>
  <div class="container-fluid text-center"id="trigger2">
    <div class="row padded">
      <div class="col-xs-offset-2 col-xs-8 bordered-orange">
        <h3>6 bonnes raisons de faire appel à Open Up coaching & consulting</h3>
      </div>
    </div>
    <div class="row padded">
      <div class="card-benefit col-xs-6 col-sm-4">
        <%= image_tag "trust.png", class: "icon" %>
        <p>Dans un climat de confiance mutuelle, profond respect et confidentialité, vous profitez d’un moment privilégié pour vous occuper de vous.</p>
      </div>
      <div class="card-benefit col-xs-6 col-sm-4">
        <%= image_tag "conversation.png", class: "icon" %>
        <p>Notre partenariat, basé sur la bienveillance et la co-responsabilité, vous permet de découvrir des solutions adaptées à votre personnalité.</p>
      </div>
      <div class="card-benefit col-xs-6 col-sm-4">
        <%= image_tag "flag.png", class: "icon" %>
        <p>Grâce à un questionnement personnel, vous prenez du recul sur votre situation, déterminez votre objectif, identifiez vos freins, vos talents et vos forces.</p>
      </div>
      <div class="card-benefit col-xs-6 col-sm-4">
        <%= image_tag "light.png", class: "icon" %>
        <p>Avec des méthodes et exercices ludiques et variées, votre créativité va être stimulée pour construire et mettre en œuvre votre plan d’action et atteindre votre objectif.</p>
      </div>
      <div class="card-benefit col-xs-6 col-sm-4">
        <%= image_tag "confidence.png", class: "icon" %>
        <p>Des bénéfices appréciés comme : une meilleure connaissance de vous et de vos besoins, une confiance et une énergie accrues, une plus grande assurance pour atteindre vos buts sur la durée.</p>
      </div>
      <div class="card-benefit col-xs-6 col-sm-4">
        <%= image_tag "calendar.png", class: "icon" %>
        <p>Des séances de 1h à 1h30 espacées de 1 à 3 semaines, en face à face, par téléphone ou par skype, en français ou en anglais pour s’adapter à vos besoins avec flexibilité.</p>
      </div>
    </div>
  </div>

  <div class="container-fluid text-center">
    <div class="row bg-blue padded">
      <div class="col-xs-offset-2 col-xs-8">
        <div class="row">
          <h4>Envie d’en savoir plus sur mon offre ?</h4>
        </div>
        <div class="row">
          <button class="btn transparent white" data-toggle="modal" data-target="#contactform" id="contact-form-button2"><%= "Contactez-moi !"%></button>

      <!-- Modal -->
          <div class="modal fade" id="contactform" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">

                <div class="modal-body" style= "background-color: #ECF0F1; border-radius: 3px;">
                  <body id="public">
                  <div id="container" class="ltr">
                    <%= render "shared/form" %>
                  </div>
                </div>
              </div>
            </div>
          </div>

        <!-- end Modal -->
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row padded text-center">
      <div class="col-xs-12 col-sm-6">
        <div class="row">
          <div class="col-xs-0 col-sm-1">
          </div>
          <div class="col-xs-12 col-sm-10">
            <h4>Votre coach : Claire de Rengervé, coach certifiée ICF</h4>
            <%= image_tag "photclaire.png", class: "avatar" %>
            <p>Claire vous accompagne pour développer votre sérénité et confiance, atteindre vos objectifs et ouvrir de nouvelles perspectives dans votre vie.</p>
          </div>
          <div class="col-xs-0 col-sm-1">
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 bordered-left-grey-big-devices">
        <h4>Ils en parlent</h4>
        <%= render "shared/owlcarousel" %>
      </div>
    </div>
  </div>

</body>

app/views/pages/monoffre.html.erb
<h1>Pages#monoffre</h1>
<p>Find me in app/views/pages/monoffre.html.erb</p>

app/views/pages/offreentreprises.html.erb
<body>

  <div class="row">
    <div id="banner-home" style= "background: linear-gradient(rgba(0, 9, 0, 0.15),rgba(0, 9, 0, 0.15)),url(<%= asset_path 'pro.png' %>); background-size:cover;" class="col-xs-12">
      <div class="row padded fadeInAndSlideDown">
        <div>
          <h1>Phrase d'accroche entreprises</h1>
        </div>
      </div>
      <div class="row text-center" style="position: static; padding-top: 90px">
        <div class="col-xs-12">
          <div id="trigger1" style="text-align:center;">
            <%= link_to "#trigger2" do %>
              <i class="fa fa-angle-down pulse scroll-btn-white" style="font-size: 55px"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid" style= "background: url(<%= asset_path 'layerbannerpros.png' %>); background-size:cover;">
    <div class="row padded text-center">
      <h2>
        Quelle est votre situation ?
      </h2>
      <%= image_tag "linestyle.png", class: "linestyle" %>
    </div>
    <div class="row padded">
      <div class="col-xs-offset-1 col-xs-10">
        <div class="row">
          <div class="col-xs-12 col-sm-4">
            <u><h4>Stress</h4></u>
            <p>Vos salariés souffrent d’une pression accrue ? Ils se plaignent d’être souvent trop stressés ?</p>
            <p>Ils ne sont pas les seuls, hélas. Le stress est aujourd’hui une des premières sources de mal-être, d’absentéisme et d’inefficacité au sein des entreprises.</p>
          </div>
          <div class="col-xs-12 col-sm-4">
            <u><h4>Expatriation</h4></u>
            <p>Dans le cadre de votre développement à l’international, les expatriés jouent un rôle clé. Partir travailler et vivre à l’étranger est un défi très motivant et en même temps en grand bouleversement de vie pour l’expatrié et sa famille. La plupart d’entre eux se plaignent d’être peu ou mal accompagnés par leur entreprise et de faire face seuls à des situations difficiles.</p>
          </div>
          <div class="col-xs-12 col-sm-4">
            <u><h4>Efficacité</h4></u>
            <p>Certains de vos salariés sont démotivés, manquent d’intérêt et d’entrain dans leur poste ? D’autres ne se sentent pas à la hauteur de leurs nouvelles responsabilités ? Ont des difficultés liées à la communication, au management de leur équipe, à l’organisation de leur travail… </p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-4">
            <p>Vous avez décidé de mettre en place une politique de prévention des risques psycho-sociaux et d’améliorer le bien-être, la fidélité et l’efficacité de vos salariés en réduisant leur stress.</p>
          </div>
          <div class="col-xs-4">
            <p>Vous avez décidé de les préparer avant le départ aux conditions clés du succès, de les soutenir pendant leur intégration, leur prise de poste, d’aider le conjoint à trouver sa nouvelle voie professionnelle en expatriation et de les accompagner également au retour en France pour bien rebondir et reprendre leurs marques.</p>
          </div>
          <div class="col-xs-4">
            <p>Vous souhaitez les aider à développer leur potentiel, à mieux connaître leur personnalité et leur source de motivation durable, à améliorer leur communication, management et booster leur efficacité.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class="container-fludi">
    <div class="row padded text-center">
      <h2>
        Quelle est notre réponse ?
      </h2>
      <p>
        Sur chacun de ces sujets, nous aidons vos salariés avec des solutions sur mesure, en fonction de vos besoins par différents types d’accompagnement individuels ou collectifs :
      </p>

    </div>
    <div class="row">
      <div class="col-xs-offset-1 col-xs-10">
        <div class="row">
          <div class="col-xs-6 padded">
            <u><h4>Coaching individuel : </h4></u>
            <p>
              <li>Entre 6 à 12 séances de 1h30, qui s’étalent sur 2 à 6 mois</li>
              <li>un entretien avec le responsable hiérarchique du coaché et éventuellement le responsable des ressources humaines et le coaché, au démarrage pour définir le besoin et les attentes et à la fin pour faire le bilan du coaching</li>
              <li>un contrat pour formaliser l’objectif de la mission, le type d’intervention, les règles et les conditions</li>
            </p>
            <p>Les séances se déroulent soit en face à face, soit par skype, en français ou en anglais.Lien vers les 3 thèmes et la méthode utilisée</p>
          </div>
          <div class="col-xs-6 padded">
            <u><h4>Formations et ateliers</h4></u>
            <p>OpenUp Coaching propose avec ses partenaires des stages de formation ou des ateliers sur des thèmes comme la gestion du stress, la gestion relationnelle, la préparation à l’expatriation, la recherche d’emploi pendant ou au retour de l’expatriation… et s ’adapte également à vos besoins en personnalisant ses services en fonction de vos attentes.Ces formations et ateliers sont très interactifs, sont structurés pour optimiser la dynamique de groupe et l’intelligence collective. Créativité, bienveillance et expérimentation sont au cœur de nos priorités pour favoriser l’engagement et l’apprentissage des participants.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/pages/offreparticuliers.html.erb
<h1>Pages#offre particuliers</h1>
<p>Find me in app/views/pages/monoffre.html.erb</p>

app/views/pages/temoignages.html.erb
<h1>Pages#temoignages</h1>
<p>Find me in app/views/pages/temoignages.html.erb</p>

app/views/shared/_footer.html.erb
<footer class="footer-distributed <%= yield(:footer_class) %>">
  <div class="row">
    <div class="col-xs-offset-2 col-xs-8">
      <div class="row text-center bordered padded">
        <div class="col-xs-6">
          <div class="row title-section-footer">
            <h5>ma boite</h5>
          </div>
          <div class="row">
            <%= link_to apropos_path do %>
              <p>alors</p>
            <% end %>
            <%= link_to temoignages_path do %>
              <p>cgv</p>
            <% end %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="row title-section-footer">
            <h5>Me suivre</h5>
          </div>
          <div class="row">
            <p><%= link_to "https://www.facebook.com/pages/Le-Gastronome-MTL/477179479106260", target:"blank" do %>
              <i class="fa fa-linkedin-square social" aria-hidden="true"></i>
            <% end %></p>
          </div>
        </div>
      </div>
      <div class="row text-center padded">
        <p>Développé avec <i class="fa fa-heart-o"></i> par paon agency </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_form.html.erb
<form id="form1" name="form1" class="wufoo topLabel page" accept-charset="UTF-8" autocomplete="off" enctype="multipart/form-data" method="post"
      action="https://legastronome.wufoo.com/forms/m1pf33kl0kimw2r/#public">

<header id="header" class="info">
<h2>Contact</h2>
<div>Vous souhaitez vous inscrire à une sesssion ? Laissez-nous votre contact.</div>
</header>

<ul>

<li id="foli17" class="notranslate      ">
<label class="desc" id="title17" for="Field17">
Prénom
</label>

<div>
<input id="Field17" name="Field17" type="text" class="field text medium" value="" maxlength="255" tabindex="1" onkeyup=""       required />
</div>
</li>
<li id="foli16" class="notranslate      ">
<label class="desc" id="title16" for="Field16">
Nom
</label>
<div>
<input id="Field16" name="Field16" type="text" class="field text medium" value="" maxlength="255" tabindex="2" onkeyup=""       required />
</div>
</li>



<li id="foli6" class="notranslate      ">
<label class="desc" id="title6" for="Field6">
Nom de votre entreprise

</label>
<div>
<input id="Field6" name="Field6" type="text" class="field text medium" value="" maxlength="255" tabindex="1" onkeyup=""       required />
</div>
</li>
<li id="foli3" class="notranslate      ">
<label class="desc" id="title3" for="Field3">
Courriel

</label>
<div>
<input id="Field3" name="Field3" type="email" spellcheck="false" class="field text medium" value="" maxlength="255" tabindex="2"       required />
</div>
</li>
<li id="foli5" class="notranslate      ">
<label class="desc" id="title5" for="Field5">
Numéro de téléphone

</label>
<div>
<input id="Field5" class="field text medium" name="Field5" tabindex="3" required
type="tel" maxlength="255" value="" />
</div>
</li>
<li id="foli4"
class="notranslate      "><label class="desc" id="title4" for="Field4">
Message

</label>

<div>
<textarea id="Field4"
name="Field4"
class="field textarea medium"
spellcheck="true"
rows="10" cols="50"

tabindex="4"
onkeyup=""
      required  ></textarea>

</div>
<li>
<div>
<input id="saveForm" name="saveForm" class="btn btn-primary" type="submit" value="Envoyer"/>
</div>
</li>

<li class="hide">
<label for="comment">Do Not Fill This Out</label>
<textarea name="comment" id="comment" rows="1" cols="1"></textarea>
<input type="hidden" id="idstamp" name="idstamp" value="oGdLris3BXoBtupf1LuUszcvLwcMU4WVUZiGUGQC+r8=" />
</li>
</ul>
</form>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
<!--     <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Notification -->
<!--     <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %> -->

    <!-- Profile picture and dropdown -->


    <%= link_to '/apropos', class: "navbar-wagon-item navbar-wagon-link" do %>
      A propos
    <% end %>
    <%= link_to '/offreparticuliers', class: "navbar-wagon-item navbar-wagon-link" do %>
      Offre particuliers
    <% end %>
    <%= link_to '/offreentreprises', class: "navbar-wagon-item navbar-wagon-link" do %>
      Offre entreprises
    <% end %>
    <%= link_to '/temoignages', class: "navbar-wagon-item navbar-wagon-link" do %>
      Témoignages
    <% end %>
    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Contactez-moi"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to '/apropos', class: "navbar-wagon-item navbar-wagon-link" do %>
            A propos
          <% end %>
        </li>
        <li>
          <%= link_to '/offreparticuliers', class: "navbar-wagon-item navbar-wagon-link" do %>
            Offre particuliers
          <% end %>
        </li>
        <li>
          <%= link_to '/offreentreprises', class: "navbar-wagon-item navbar-wagon-link" do %>
            Offre entreprises
          <% end %>
        </li>
        <li>
          <%= link_to '/temoignages', class: "navbar-wagon-item navbar-wagon-link" do %>
            Témoignages
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_owlcarousel.html.erb
<div class="owl-carousel">
 <div class= "text-center item">
    <div class="row">
      <div class="col-xs-0 col-sm-1">
      </div>
      <div class="col-xs-12 col-sm-10">
        <%= link_to "/temoignages" do %>
          <h5> "D’abord dubitatif, j’ai pu, lors de ces séances de coaching réfléchir aux améliorations à apporter à mes compétences professionnelles et à ma relation avec mes collègues ; l’objectif étant de m’améliorer dans mes fonctions."</h5>
          <p>Bob Marley - expert technique chez Faurecia</p>
        <% end %>
      </div>
      <div class="col-xs-0 col-sm-1">
      </div>
    </div>
  </div>
  <div class= "text-center item">
    <div class="row">
      <div class="col-xs-0 col-sm-1">
      </div>
      <div class="col-xs-12 col-sm-10">
        <%= link_to "/temoignages" do %>
          <h5> "D’abord dubitatif, j’ai pu, lors de ces séances de coaching réfléchir aux améliorations à apporter à mes compétences professionnelles et à ma relation avec mes collègues ; l’objectif étant de m’améliorer dans mes fonctions."</h5>
          <p>Kelly Slater - cadre chez EDF</p>
        <% end %>
      </div>
      <div class="col-xs-0 col-sm-1">
      </div>
    </div>
  </div>
  <div class= "text-center item">
    <div class="row">
      <div class="col-xs-0 col-sm-1">
      </div>
      <div class="col-xs-12 col-sm-10">
        <%= link_to "/temoignages" do %>
          <h5> "D’abord dubitatif, j’ai pu, lors de ces séances de coaching réfléchir aux améliorations à apporter à mes compétences professionnelles et à ma relation avec mes collègues ; l’objectif étant de m’améliorer dans mes fonctions."</h5>
          <p>Julia Roberts - Community leader chez sanofi</p>
        <% end %>
      </div>
      <div class="col-xs-0 col-sm-1">
      </div>
    </div>
  </div>
</div>